name: habit_tracker_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  rxdart: ^0.27.0
  sqflite: ^2.0.0
  path: ^1.8.0
  get_it: ^7.2.0
  intl: ^0.18.0 # Reverted to latest version
  flutter_colorpicker: ^1.0.3
  animated_text_kit: ^4.2.1
  flutter_animate: ^4.2.0
  fl_chart: ^0.67.0 # Replaced charts_flutter with fl_chart
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/motivation1.jpg
    - assets/images/motivation2.jpg
    - assets/images/motivation3.jpg
    - assets/images/quote1.jpg
    - assets/images/quote2.jpg
    - assets/images/quote3.jpg