name: habit_tracker_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  rxdart: ^0.28.0
  sqflite: ^2.3.3
  path: ^1.9.0
  get_it: ^7.7.0
  intl: ^0.20.2
  flutter_colorpicker: ^1.1.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.5.0
  fl_chart: ^0.68.0
  http: ^1.2.2
  table_calendar: ^3.1.2
  url_launcher: ^6.3.0
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/motivation1.jpg
    - assets/images/motivation2.jpg
    - assets/images/motivation3.jpg
    - assets/images/quote1.jpg
    - assets/images/quote2.jpg
    - assets/images/quote3.jpg